<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>RuleforgeTD.BalanceCli.Tests</RootNamespace>
    <AssemblyName>Ruleforge.BalanceCli.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Tools/Ruleforge.BalanceCli/Ruleforge.BalanceCli.csproj" />
    <ProjectReference Include="../../Tools/Ruleforge.GameLogic.Net/Ruleforge.GameLogic.Net.csproj" />
  </ItemGroup>
</Project>
